language: c++

before_script: cd unit_test
script:
  - cmake .
  - make
  - ./oel-test

branches:
  only:
    - master
    - develop

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode7.3
