language: c++

before_script: cd unit_test
script:
  - cmake -D CMAKE_BUILD_TYPE=$MY_BUILD_TYPE .
  - make
  - ./oel-test

branches:
  only:
    - master
    - develop
    - /release/

jobs:
  include:
    - os: linux
      dist: xenial
      env:
        - CXXFLAGS="-D OEL_MEM_BOUND_DEBUG_LVL=2" MY_BUILD_TYPE=Debug
    - os: linux
      arch:
        - arm64
      env:
        - MY_BUILD_TYPE=Release
    - os: linux
      dist: bionic
      env:
        - CC=gcc-10 CXX=g++-10  MY_BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-10
    - os: osx
      osx_image: xcode12.2
      env:
        - CXXFLAGS="-fsanitize=address -fsanitize=undefined -D OEL_MEM_BOUND_DEBUG_LVL=0" MY_BUILD_TYPE=""
