language: c++

before_script: cd unit_test
script:
  - cmake -D CMAKE_BUILD_TYPE=$MY_BUILD_TYPE -D CMAKE_CXX_STANDARD=$MY_CXX_STD .
  - make
  - ./oel-test

branches:
  only:
    - master
    - develop
    - /release/

os:
  - linux
jobs:
  include:
    - dist: xenial
      env:
        - CXXFLAGS="-D OEL_MEM_BOUND_DEBUG_LVL=2" MY_BUILD_TYPE=Debug MY_CXX_STD=14
    - arch: arm64
      dist: focal
      compiler: clang
      env:
        - CXXFLAGS="-D OEL_MEM_BOUND_DEBUG_LVL=2" MY_BUILD_TYPE=Debug MY_CXX_STD=20
    - arch: arm64-graviton2
      virt: lxd
      group: edge
      dist: focal
      env:
        - CC=gcc-10 CXX=g++-10  MY_BUILD_TYPE=Release MY_CXX_STD=20
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-10
    - os: osx
      osx_image: xcode7.3
      env:
        - MY_BUILD_TYPE=Release MY_CXX_STD=14
    - os: osx
      osx_image: xcode13.1
      env:
        - CXXFLAGS="-fsanitize=address -fsanitize=undefined" MY_BUILD_TYPE="" MY_CXX_STD=20
