language: c++

before_script: cd unit_test
script:
  - cmake .
  - make
  - ./oel-test

branches:
  only:
    - master
    - develop

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      env: CC="gcc-9" CXX="g++-9"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
    - os: osx
      osx_image: xcode11.1
